name: Deploy Client to Vercel

on:
  push:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  installDependencies:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
        
      - name: Install Dependencies
        run: npm run installFEDependencies
  build:
      runs-on: ubuntu-latest
      needs: installDependencies
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
        
      - name: Build
        working-directory: client
        run: npm run build
         
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel deploy --prod --token ${{ secrets.BACKEND_VERCEL_TOKEN }} --project-id ${{ secrets.BACKEND_PROJECT_ID }} --org-id ${{ secrets.ORG_ID }}
